# Generated by Django 4.2.1 on 2023-06-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_direccion_usuario_id_alter_factura_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='imagesPropducts/')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.producto')),
            ],
        ),
    ]
