# Generated by Django 4.2.1 on 2023-06-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_imagen_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_corta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_larga',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
